// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ8xKXdxVMNrLM04CrliuIDB7X1fK2a7k',
    appId: '1:1063258773943:web:c720068868fb59d04a3032',
    messagingSenderId: '1063258773943',
    projectId: 'gerenciador-cotacoes',
    authDomain: 'gerenciador-cotacoes.firebaseapp.com',
    databaseURL: 'https://gerenciador-cotacoes-default-rtdb.firebaseio.com',
    storageBucket: 'gerenciador-cotacoes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwT6g7TIEzLRn79LAHH0oz1RX1J4zak70',
    appId: '1:1063258773943:android:5ee6d6ac914a4aee4a3032',
    messagingSenderId: '1063258773943',
    projectId: 'gerenciador-cotacoes',
    databaseURL: 'https://gerenciador-cotacoes-default-rtdb.firebaseio.com',
    storageBucket: 'gerenciador-cotacoes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Lk-YBiIutkf6e2y3wSuC1QhNLfa3Meg',
    appId: '1:1063258773943:ios:4a335be9388a7b394a3032',
    messagingSenderId: '1063258773943',
    projectId: 'gerenciador-cotacoes',
    databaseURL: 'https://gerenciador-cotacoes-default-rtdb.firebaseio.com',
    storageBucket: 'gerenciador-cotacoes.appspot.com',
    iosClientId: '1063258773943-so9cpqmkju6aacu9ioavkmdq0asn83m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gerenciadorCot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Lk-YBiIutkf6e2y3wSuC1QhNLfa3Meg',
    appId: '1:1063258773943:ios:4a335be9388a7b394a3032',
    messagingSenderId: '1063258773943',
    projectId: 'gerenciador-cotacoes',
    databaseURL: 'https://gerenciador-cotacoes-default-rtdb.firebaseio.com',
    storageBucket: 'gerenciador-cotacoes.appspot.com',
    iosClientId: '1063258773943-so9cpqmkju6aacu9ioavkmdq0asn83m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gerenciadorCot',
  );
}
